require("cloud/jobs/campaign")
require("cloud/jobs/chargeUser")
require("cloud/jobs/stripeRegister")
require("cloud/jobs/messagesSlack")
require("cloud/jobs/assignmentsSlack")
require("cloud/jobs/statsSlack")
require("cloud/jobs/feedbackSMS")
require("cloud/jobs/metrics")
